// Blacklist of words
const blacklist = {
    suicidal: [
      "suicide", "kill myself", "end it all", "hopeless", "no reason to live", 
      "nobody cares", "die", "dying", "want to die", "self-harm", "cutting", "cut myself",
      "overdose", "goodbye forever", "leave forever", "hanging", "jumping off",
      "suicidal", "commit suicide", "committed suicide", "thinking about suicide", 
      "killed myself", "killing myself", "ending my life", "life is over", "taking too many pills", 
      "took pills", "hurting myself", "no one cares if I die", "better off dead", "wish I was gone", 
      "disappear forever", "leave this world", "give up on life", "given up on life", "there’s no point", 
      "too much pain to handle", "it’s too much", "nobody would notice if I’m gone", "life is meaningless", 
      "life is pointless", "I’m done", "I’ve had enough", "can’t go on anymore", "no hope left", 
      "wish I never existed", "can’t take it anymore", "don’t want to wake up", "want to disappear", 
      "nobody loves me", "everyone hates me", "I’m a burden", "burden to everyone", "wish I could die", 
      "death is better", "no one needs me", "useless existence", "tired of life", "life is unbearable", 
      "waste of space", "waste of life", "I shouldn’t exist", "I shouldn’t be here", 
      "no one would care if I disappeared", "tired of everything", "drained from life", 
      "wish I was dead", "I don’t matter", "existence is painful", "living is hard", "it hurts to live", 
      "too broken to fix", "can’t fix this", "why am I here", "nothing matters anymore", "want to sleep forever",
      "life hurts", "hurting inside", "tired of feeling this way", "I’m broken", "broken inside", "lost hope",
      "feeling abandoned", "no way out", "all alone in this world", "no one listens", "crying for help",
      "the pain is unbearable", "I’m not okay", "I’m falling apart", "falling into darkness", 
      "wish I could end it", "struggling to stay alive", "holding on by a thread", "wanting to escape",
      "there’s no escape", "the world is better without me", "everyone is better without me", 
      "I can’t do this anymore", "wanting to fade away", "feeling like a ghost", "drowning in sadness", 
      "overwhelmed by life", "it’s all too much", "breaking under pressure", "can’t handle the pain",
      "overwhelmed by despair", "sinking into darkness", "lost the will to live", "can’t find joy anymore", 
      "life feels empty", "completely alone", "why does it hurt so much", "numb to everything", "no escape from this",
      "the end feels near", "reaching my breaking point", "no light at the end of the tunnel", "suffocating from the pain",
      "tears won’t stop", "my heart is heavy", "can’t carry this weight anymore", "this pain is killing me",
    ],
    bodyImage: [
      "fat", "ugly", "disgusting", "too skinny", "body shaming", "obese", 
      "starve", "starving", "diet", "too much weight", "overweight", "anorexic", 
      "bulimic", "eat less", "no one likes how I look",
      "too fat", "gross", "unattractive", "too big", "too small", "look terrible", "hate my body", 
      "hating my body", "body image issues", "bad body", "my body is disgusting", "ashamed of my body", 
      "my body is my enemy", "hideous", "horrible appearance", "disfigured", "I look gross", 
      "not good enough", "wish I looked different", "not pretty enough", "don’t feel attractive", 
      "feel ugly", "feeling ugly", "feel fat", "feeling fat", "everyone thinks I’m fat", "don’t like my reflection", 
      "feel unattractive", "I hate my weight", "I’m ashamed of my size", "hate seeing myself in the mirror", 
      "wish I was thinner", "wish I was skinnier", "feel fat all the time", "too big to be loved", 
      "I’m not attractive", "ugliest person alive", "I look awful", "everyone thinks I’m ugly", 
      "nobody compliments my appearance", "feel insecure about my looks", "feel horrible about myself", 
      "weight issues", "struggling with my size", "hate my reflection", "want to look different", "horrible body image",
      "body dysmorphia", "struggling to love myself", "feeling too heavy", "not skinny enough", "feeling bloated",
      "too short", "too tall", "hate my proportions", "nobody likes my appearance", "I don’t fit in",
      "wish I had a better body", "nobody finds me attractive", "I look out of place", "can’t stand looking at myself",
      "feel too wide", "feel too narrow", "nothing fits me", "I’m so unattractive", "people judge me for my weight",
      "embarrassed by my size", "feel awkward in my own skin", "I look like a mess", "struggling to find confidence",
      "I’m not proportionate", "I’m too bulky", "I’m too frail", "nobody notices me", "feel invisible because of my looks",
      "can’t fix my body", "wish I had a different face", "wish I had different features", "my body feels wrong",
      "stuck in a body I hate", "nobody accepts me", "feel ugly and worthless", "not photogenic", "I’m ashamed to go out",
      "don’t want people to see me", "hate my skin", "my body is my biggest insecurity", "always feel judged",
      "I look awkward in pictures", "nobody compliments my looks", "feel horrible about my weight", "wish I could change myself",
      "too big for this world", "feel too small to matter", "can’t look in the mirror", "my body doesn’t belong to me",
      "wish I could disappear because of how I look",
    ],
    shaming: [
        "loser", "failure", "stupid", "idiot", "pathetic", "worthless", "nobody likes you", 
        "you can’t do anything", "dumb", "hopeless", "moron", "lame", "useless", 
        "shame on you", "you’re nothing", "embarrassing", "weak", "clown", "trash",
        "you’re a failure", "you failed", "you’re useless", "you’re embarrassing", "you’re a disgrace", 
        "you’ll never succeed", "you’ll never amount to anything", "you’re a waste of space", 
        "you’re a waste of time", "everyone hates you", "no one respects you", "you’re not good enough", 
        "you’re inferior", "you’re incapable", "you’ll never do anything right", "you’re a nobody", 
        "everyone is laughing at you", "you’re a laughingstock", "you’re a failure in life", 
        "you’re an embarrassment to everyone", "you’re the worst", "no one wants you around", 
        "everyone wishes you were gone", "you’re pathetic", "no one cares about you", "nobody values you", 
        "you’ll never fit in", "you're a joke", "you’ll never make it", "no one believes in you", 
        "you don’t matter", "you’re a disappointment", "you’re not good enough for anyone", "you’re not capable", 
        "nobody will ever love you", "no one will miss you", "you’re always wrong", "you’re always messing up", 
        "people are embarrassed by you", "you're worthless", "you’re a failure in everything", "you’re invisible", 
        "no one listens to you", "nobody cares about your opinion", "you’ve got nothing to offer", 
        "you’re always making mistakes", "you’ll never be happy", "people laugh behind your back", 
        "you're always in the way", "no one’s ever proud of you", "everyone feels sorry for you", 
        "you're not even worth talking to", "you’re a burden", "you're just wasting space", "you have no future", 
        "you’re not good enough to succeed", "no one wants to see you win", "you're always alone", 
        "you're always the problem", "no one takes you seriously", "you’re irrelevant", "you’re not important", 
        "everyone finds you annoying", "you're always the last one picked", "nobody cares about your feelings", 
        "you’re a mess", "no one trusts you", "everyone’s just pretending to like you", "you’re unworthy", 
        "no one cares what you think", "you're always failing", "you’re always a disappointment", 
        "nobody understands you", "you’re just a burden on society", "people only pity you", "no one is happy for you", 
        "you’ve got no chance", "people only tolerate you", "you’re just taking up space", "you don’t deserve anything", 
        "you’re useless to everyone", "you'll never find success", "no one wants you around", "you’re not strong enough", 
        "you’re too weak", "you're a mistake", "you’ve ruined everything", "everyone’s sick of you", "you’re an outcast"
      ],
      
      bullying: [
        "hate you", "nobody likes you", "go away", "idiot", "you’re the worst", 
        "shut up", "no one cares", "you’re nothing", "annoying", 
        "get lost", "crybaby", "fat pig", "ugly face", "get a life", "stupid kid", 
        "trash", "worthless person", "go die", "nobody loves you", "dumb",
        "you’re pathetic", "you’ll never amount to anything", "everyone hates you",
        "you don’t belong", "nobody cares about you", "you’re not worth anyone’s time", 
        "everyone’s laughing at you", "you’re so annoying", "you’re a failure", "no one will miss you", 
        "shut up, nobody cares", "nobody needs you", "you’re a loser", "you can’t do anything right", 
        "everyone hates your voice", "nobody wants you here", "nobody respects you", 
        "everyone is judging you", "you're not welcome", "you’re so stupid", "nobody wants to be around you", 
        "you’re a joke", "you're too ugly", "stop talking", "everyone’s tired of you", 
        "you’re useless", "no one wants to listen to you", "you’ll never be anything", "you’re nothing to us", 
        "you’re just a burden", "stop pretending you’re important", "no one cares about your problems", 
        "everyone’s sick of hearing about you", "just leave", "you’re embarrassing", "stop existing", 
        "you’re too weird", "you don’t deserve friends", "no one wants you", "you don’t fit in", 
        "everyone laughs at you", "you’re a freak", "get lost, nobody cares", "you’ll never be loved", 
        "you’re annoying as hell", "nobody cares about your opinions", "people talk behind your back", 
        "everyone avoids you", "just go away", "you’re worthless to me", "you’ll never be good enough", 
        "you’re not worth anyone’s attention", "nobody is ever proud of you", "you don’t deserve friends", 
        "no one cares if you live or die", "just quit already", "you’ll never fit in", "no one wants you here", 
        "you're a mistake", "people make fun of you", "you're pathetic", "nobody is here for you", 
        "you’re the worst thing ever", "stop pretending to be someone you’re not", "nobody likes your attitude", 
        "you’ll never amount to anything", "you’ll always be alone", "no one wants to be seen with you", 
        "you’re just in the way", "nobody will care if you leave", "nobody loves you", "you’re too annoying", 
        "stop trying to be someone you’re not", "nobody will stand up for you", "everyone feels sorry for you", 
        "you're just an embarrassment", "no one trusts you", "you’re a waste of space", "you’re the least important", 
        "nobody wants to talk to you", "you’re too sensitive", "stop being so pathetic", "just go away", 
        "no one will ever notice you", "you're such a loser", "you're an embarrassment to your family", 
        "you're useless to us", "no one likes anything about you", "nobody cares what happens to you", 
        "you’re not worth anyone’s time", "no one ever wants to hear your opinions", "you’ll never fit in with anyone", 
        "you’ll never be successful", "everyone’s ashamed of you", "nobody wants you around", "you’ll never get ahead"
      ]
    };